# Generated by Django 3.1.6 on 2021-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pemail',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
